# Generated by Django 4.2.5 on 2023-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture_type', models.CharField(default='TH', max_length=100, verbose_name='Lecture code')),
                ('Lecture_type_ff', models.CharField(default='Theory', max_length=100, verbose_name='Lecture Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_instance',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_code',
            field=models.CharField(default='CODE', max_length=100),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_current_sem',
            field=models.BooleanField(default=True, verbose_name='Current Semester'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_current_sem',
            field=models.BooleanField(default=True, verbose_name='Current Semester'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
