# Generated by Django 4.2.5 on 2023-09-24 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_faculty_remove_timetable_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=100, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lecture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lecture', verbose_name='Lecture Type'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='timing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timing', verbose_name='Timing'),
        ),
    ]
