# Generated by Django 4.2.5 on 2023-09-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetableentry_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='timetable',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetable'),
        ),
    ]
