# Generated by Django 4.2.5 on 2023-09-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetableentry_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='course_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
