# Generated by Django 4.2.5 on 2023-09-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_timetable_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.course'),
        ),
    ]
