# Generated by Django 4.2.5 on 2023-10-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetableentry_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.course', verbose_name='course'),
        ),
    ]
