# Generated by Django 4.2.5 on 2023-10-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_timetable_section_alter_section_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='faculty_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_3', to='timetable.faculty', verbose_name='Faculty 3 (for lab)'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='faculty_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_4', to='timetable.faculty', verbose_name='Faculty 4 (for lab)'),
        ),
    ]
