# Generated by Django 4.2.5 on 2023-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_timetableentry_faculty_3_timetableentry_faculty_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='salutation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
