# Generated by Django 4.2.5 on 2023-10-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_faculty_salutation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='salutation_name',
            new_name='salutation',
        ),
    ]
